/*
 * Native class adapter template for 'moduleA.StringNativeClass'.
 * WARNING: remember to copy this file to your project dir before you begin to change it.
 * Generated by the Coral Compiler v0.7.0 on Thu Mar 01 15:35:26 2012.
 */

#include "StringNativeClass_Adapter.h"

namespace moduleA {

const co::Any& StringNativeClass_Adapter::getState( moduleA::StringNativeClass& instance )
{
	static co::Any returnValue;
	returnValue.set<std::string&>( instance.data );
	return returnValue;
}

void StringNativeClass_Adapter::setState( moduleA::StringNativeClass& instance, const co::Any& state )
{
	instance.data = state.get<std::string&>();
}

const std::string& StringNativeClass_Adapter::getValue( moduleA::StringNativeClass& instance )
{
	return instance.data;
}

void StringNativeClass_Adapter::setValue( moduleA::StringNativeClass& instance, const std::string& value )
{
	instance.data = value;
}

} // namespace moduleA
